### PR TITLE
Fix compilation issues with rustc 1.0.0-nightly

### PR DESCRIPTION
**Pull request by lavrin**
Specifically, rustc 1.0.0-nightly (170c4399e 2015-01-14 00:41:55 +0000)

I'm rather a rust newbie, so please let me know of any issues. Specifically, I'm not the happiest about repeating [the match on `(color_type, pixel_width)`](https://github.com/lavrin/rust-png/commit/b53cc19f25a920af376480d15bb259691dec464a#diff-b4aea3e418ccdb71239b96952d9cddb6L134), but without that the compilation failed with:

```
src/lib.rs:133:41: 140:10 error: match arms have incompatible types:
 expected `(fn(collections::vec::Vec<u8>) -> PixelsByColorType {RGBA8}, _)`,
    found `(fn(collections::vec::Vec<u8>) -> PixelsByColorType {K8}, _)`
```

If there's a better way, I'm all ears.

### CODE REVIEW

**Comment by jdm** [comment]
We have a branch that compiles with the 1.0 alpha - rustup_20150109. I'd prefer to rebase these changes on top of that branch and merge them in order.

**Comment by lavrin** [comment]
Haha, too bad I haven't noticed that earlier. Still, a nice learning exercise for me. Please disregard this PR, it only touches things already fixed in rustup_20150109. Thanks.

**Comment by jdm** [comment]
Thanks for the PR, regardless :)
